Repository ucsb-cs156-w24/proj-gauchoride-w24-7pm-4, pull requests merged in 2024-03, with the labels that each got.

#22 Wt driver availability record and fixtures
  frontend/src/fixtures/driverAvailabilityFixtures.js
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverAvailability.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverAvailabilityRepository.java
Labels: Merge Candidate, 10

#23 Wt driver availability post endpoint
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverAvailability.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate, 10

#25 fixed issue with ROLE_RIDER not working
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/stories/components/Nav/AppNavbar.stories.js
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptorTests.java
Labels: Merge Candidate, 5

#28 DELETE for Driver Availability Controller (Driver Availability)
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate

#29 Wt driver availability admin get all endpoint and get by id endpoint
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate, 5

#34 FEATURE: All users should not be able to see "Apply to be a Rider" if they are a rider
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: Merge Candidate, 5

#35 fixed chat display
  frontend/src/main/components/ChatMessage/ChatDisplay.js
  frontend/src/main/components/ChatMessage/ChatMessageDisplay.js
Labels: 5

#37 Table component for Driver Availability plus tests
  frontend/src/App.js
  frontend/src/main/components/DriverAvailability/DriverAvailabilityTable.js
  frontend/src/main/utils/driverAvailabilityUtils.js
  frontend/src/stories/components/DriverAvailability/DriverAvailabilityTable.stories.js
  frontend/src/tests/components/DriverAvailability/DriverAvailabilityTable.test.js
  frontend/src/tests/utils/driverAvailabilityUtils.test.js
Labels: 15

#40 FEATURE: Create DriverAvailabilityCreatePage (Driver Availiability) #18
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityCreatePage.js
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityCreatePage.stories.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityCreatePage.test.js
Labels: 10

#43 FEATURE: Create DriverAvailabilityEditPage (Driver Availability)
  frontend/src/App.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityEditPage.js
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityEditPage.stories.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityEditPage.test.js
Labels: 10

#31 PUT for Driver Availability Controller (Driver Availability)
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverAvailabilityRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: 10

#41 FEATURE: Create DriverAvailabilityIndexPage (Driver Availability)
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityCreatePage.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityIndexPage.js
  frontend/src/main/pages/Ride/RideRequestIndexPage.js
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityCreatePage.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityIndexPage.test.js
Labels: 10
